### ISSUE TITLE
failed to lock index buffer in CMeshDX8::LockIndexBuffer

### ISSUE THREAD

**Issue by Skilowi** [tf2classic/tf2classic-issue-tracker#100]
Team Fortress 2 Classic installed through newest installer from website
Machine is ThinkPak T540p with iGPU and Linux Mint 20.3

Getting error on joining to any non TF2C official server

![obraz](https://user-images.githubusercontent.com/76708049/193450615-694532df-8991-4ec5-9b69-0e613a42a56c.png)

After clicking OK game closes.

**Comment by sapphonie** [comment]
> 

@skilowi please verify if this is still an issue after
- Clearing all downloaded files
- Reinstalling the game

Thanks

**Comment by newgreenshoot** [comment]
This issue is typically caused by your machine running out of video memory. Nothing we can do about it.
