### ISSUE TITLE
Odd edgecase involving a crit environmental death

### ISSUE THREAD

**Issue by AZMCode** [tf2classic/tf2classic-issue-tracker#103]
I was playing on official servers as a huntsman sniper, fired a random crit at a pyro, who reflected it, and died to fall damage at the same time.
I got killed, according to the console, by someone else with world(crit). The kill icon was `<playername> <skull and crossbones crit> <my name>`, so it would appears players have the ability to earthbend and use the world to crit kill me.

I've tried reproducing the bug in many ways but I haven't found a way to do it yet. Just so you guys are aware something rotten is in there :P

**Comment by AZMCode** [comment]
May be related to a July 10 2013 patch in live tf2

**Comment by darkwater** [comment]
Currently my best guess is it's some case that GetKillingWeaponName doesn't handle. A deflected crit tranq gun projectile results in a crit skull kill icon, but the console still says `tf_projectile_dart (crit)`.
