### ISSUE TITLE
the servers all freeze after 1 minute of joining

### ISSUE THREAD

**Issue by budspenser2315** [tf2classic/tf2classic-issue-tracker#109]
i cant play any server because they going freeze after 1 minute or less than, there is only 1 server i can play, its bigmzi custom weapons server, there is anyway to fix this problem? because i want to play other server too
there is some of the information i got from console:

**Team Fortress 2 Classic
Map: pl_alpen_rc1
Players: 24 / 27
Build: 5394425
Server Number: 1037

Attemped to precache unknown particle system "sultry_pipespray_small"!
Attemped to precache unknown particle system "sultry_pipespray_steamend"!
Attemped to precache unknown particle system "sultry_pipespray_water"!
Attemped to precache unknown particle system "sultry_last_spray_explode"!
Attemped to precache unknown particle system "sultry_last_explosion_steamend"!
Attemped to precache unknown particle system "sultry_last_waterexplode"!
Attemped to precache unknown particle system "sulry_last_waterexplode_mist"!
Attemped to precache unknown particle system "sultry_last_explosion_steamend_steam"!
Attemped to precache unknown particle system "sultry_last_explode_steamend_widesteam"!
Attemped to precache unknown particle system "last_waterexplode_close"!
Attemped to precache unknown particle system "sultry_last_explosion_splashes"!
Attemped to precache unknown particle system "sultry_last_explode_wake"!
Attemped to precache unknown particle system "sultry_last_wobblespray_extreme"!
Attemped to precache unknown particle system "sultry_last_wobblespray_extreme_water"!
Attemped to precache unknown particle system "sultry_last_wobblespray"!
Attemped to precache unknown particle system "sultry_last_wobblespray_water"!
Attemped to precache unknown particle system "sultry_last_aggressivetest"!
Attemped to precache unknown particle system "torch_fire"!
Attemped to precache unknown particle system "torch_smoke"!
Attemped to precache unknown particle system "torch_fire_nosmoke"!
Attemped to precache unknown particle system "fireflies_256"!
Attemped to precache unknown particle system "fireflies_128"!
Attemped to precache unknown particle system "fireflies_64"!
Attemped to precache unknown particle system "fireflies_512"!
Attemped to precache unknown particle system "stoneyridge_finale"!
Attemped to precache unknown particle system "stoneyridge_finale_flash_warp"!
Attemped to precache unknown particle system "stoneyridge_finale_shards2"!
Attemped to precache unknown particle system "stoneyridge_finale_pit_smoke"!
Attemped to precache unknown particle system "stoneyridge_finale_core_smokey2"!
Attemped to precache unknown particle system "stoneyridge_finale_shards"!
Attemped to precache unknown particle system "stoneyridge_finale_core_smokey"!
Attemped to precache unknown particle system "stoneyridge_finale_parent"!
Attemped to precache unknown particle system "stoneyridge_finale_flash"!
Attemped to precache unknown particle system "stoneyridge_finale_flash_follow"!
Attemped to precache unknown particle system "stoneyridge_finale_pit_core2"!
Attemped to precache unknown particle system "stoneyridge_finale_pit_core"!
Attemped to precache unknown particle system "stoneyridge_finale_pit_core3"!
Attemped to precache unknown particle system "stoneyridge_finale_pit_glow"!
Attemped to precache unknown particle system "stoneyridge_finale_pit_glow2"!
Attemped to precache unknown particle system "stoneyridge_dust"!
Attemped to precache unknown particle system "stoneyridge_finale_parent2"!
Attemped to precache unknown particle system "stoneyridge_finale_core_smokey_BACKUP1"!
Attemped to precache unknown particle system "stoneyridge_finale_parent2_BACKUP1"!
Attemped to precache unknown particle system "stoneyridge_finale_core_smokey_upwards"!
Attemped to precache unknown particle system "glow"!
Attemped to precache unknown particle system "glow_mainframe_blue"!
Attemped to precache unknown particle system "glow_mainframe_red"!
Attemped to precache unknown particle system "laser"!
Attemped to precache unknown particle system "laser_glow"!
Attemped to precache unknown particle system "laser_red"!
Attemped to precache unknown particle system "reactor_main"!
Attemped to precache unknown particle system "reactor_glow"!
Attemped to precache unknown particle system "reactor_outer_energy"!
Attemped to precache unknown particle system "reactor_outer_engery2"!
Attemped to precache unknown particle system "steam_vent"!
Attemped to precache unknown particle system "fire_large_02"!
Attemped to precache unknown particle system "fire_large_02_warp"!
Attemped to precache unknown particle system "fire_large_base"!
Attemped to precache unknown particle system "fire_large_02_fillerb"!
Attemped to precache unknown particle system "smoke_medium_01"!
Attemped to precache unknown particle system "fire_ploom_01"!
Attemped to precache unknown particle system "fire_medium_01"!
Attemped to precache unknown particle system "fire_medium_01_fillerb"!
Attemped to precache unknown particle system "fire_medium_01_fillerb Version #2"!
Attemped to precache unknown particle system "fire_incinerator_constant"!
Attemped to precache unknown particle system "fire_incinerator_heatwaver"!
Attemped to precache unknown particle system "fire_incinerator_door"!
Attemped to precache unknown particle system "fire_incinerator_constant_2"!
Attemped to precache unknown particle system "fire_incinerator_door_heatwaver"!
Attemped to precache unknown particle system "fire_incinerator_door_smoke"!
Attemped to precache unknown particle system "fire_incinerator_door_smoke_constant"!
Attemped to precache unknown particle system "fire_incinerator_heatwaver_constant"!
Attemped to precache unknown particle system "fire_incinerator_constant_end01"!
Attemped to precache unknown particle system "fire_incinerator_constant_end02"!
Attemped to precache unknown particle system "fire_incinerator_base"!
Attemped to precache unknown particle system "fire_incinerator_constant_smoke"!
Attemped to precache unknown particle system "fire_incinerator_window_base"!
Attemped to precache unknown particle system "fire_incinerator_window_constant_flames2"!
Attemped to precache unknown particle system "fire_incinerator_window_occaisional_flames"!
Attemped to precache unknown particle system "fire_incinerator_window_constant_flames"!
Attemped to precache unknown particle system "fire_incinerator_window_warp"!
Attemped to precache unknown particle system "smoke_blackbillow_blastpitt_skybox"!
Attemped to precache unknown particle system "cc_gate_destroy"!
Attemped to precache unknown particle system "cc_gate_destroy_sparks"!
Attemped to precache unknown particle system "midwest_reactor_fx"!
Attemped to precache unknown particle system "midwest_reactor_bits"!
Attemped to precache unknown particle system "midwest_reactor_rings"!
Attemped to precache unknown particle system "midwest_reactor_mist"!
Attemped to precache unknown particle system "midwest_reactor_glow"!
Attemped to precache unknown particle system "midwest_reactor_electricity"!
Attemped to precache unknown particle system "midwest_reactor_ ring_core"!
Attemped to precache unknown particle system "hadal_bubbles"!
Attemped to precache unknown particle system "hadal_rod"!
The server is using sv_pure 0.  (Enforcing consistency for select files only)
Voice_Init: Using Steam voice optimal sample rate 24000
budspenser2315 connected
Compact freed 1105920 bytes
Redownloading all lightmaps**

**Comment by budspenser2315** [comment]
i missed the last 1:
No such variable "$fogenable" for material "maps/pl_alpen_rc1/water/water_2fort_2752_-3456_-176"

**Comment by chloecormier** [comment]
Resolved, this was related to spray management plugins.
