### ISSUE TITLE
[Voice Responses] Weapon fire / swing voice responses no longer work

### ISSUE THREAD

**Issue by SilentFox3** [tf2classic/tf2classic-issue-tracker#111]
As of TF2C v2.0.4, it seems like _any_ voice responses that use "ConceptFireWeapon" as a Response Rule criteria don't do anything anymore on most classes. Using the commands `rr_debugresponses 1;developer 1` shows that firing / swinging a weapon doesn't trigger any output even when it should have done so in the Dev. Console.

The only exceptions seem to be when playing Pyro, or Heavy when he's fired a Minigun at least once since spawning. All other classes can't trigger fire wep responses at all.

As a short list, this includes: Any and all lines a class says while firing their weapons (Heavy fists swinging, Demoman drunk, Invuln shooting, Defend the point), as well as angry expressions that appear while every Class is firing their weapon but not saying anything, among a few other class-specific things.

This odd behavior may be because of a change listed in the TF2C v2.0.4 changelog;
`Scenes created by weapon firing are now cleaned up properly, making it harder to create too many edicts on a server through tap-firing`

**Comment by sapphonie** [comment]
> As of TF2C v2.0.4, it seems like _any_ voice responses that use "ConceptFireWeapon" as a Response Rule criteria don't do anything anymore on most classes. Using the commands `rr_debugresponses 1;developer 1` shows that firing / swinging a weapon doesn't trigger any output even when it should have done so in the Dev. Console.
> 
> The only exceptions seem to be when playing Pyro, or Heavy when he's fired a Minigun at least once since spawning. All other classes can't trigger fire wep responses at all.
> 
> As a short list, this includes: Any and all lines a class says while firing their weapons (Heavy fists swinging, Demoman drunk, Invuln shooting, Defend the point), as well as angry expressions that appear while every Class is firing their weapon but not saying anything, among a few other class-specific things.
> 
> This odd behavior may be because of a change listed in the TF2C v2.0.4 changelog; `Scenes created by weapon firing are now cleaned up properly, making it harder to create too many edicts on a server through tap-firing`

@silentfox3 Can you test if this is still an issue as of 2.1.1? Thanks

**Comment by SilentFox3** [comment]
Apologies for the late reply. As of TF2C v2.1.0's release a month or so ago, this issue seems to have been fixed. Seems like `ConceptFireWeapon` Responses properly trigger for all classes with no other conditions necessary, once more. Additionally, it still works fine in the latest version as of writing, TF2C v2.1.1.

This should probably be marked as resolved now - Thank you!
