### ISSUE TITLE
Crit stickies model disappearing but not their particles

### ISSUE THREAD

**Issue by DelabLeFou** [tf2classic/tf2classic-issue-tracker#113]
Was playing on Dustbowl and for some reasons, depending on my camera angle, the model for crit stickies would disappear but the particles for them would stay

https://user-images.githubusercontent.com/105130525/209541190-d4bbfc62-d8e3-429c-b0b8-3af3aed80289.mp4

**Comment by bobatealee** [comment]
technically fixed on dustbowl now, but this is going to happen on any map that has this issue. up to mappers to fix
