### ISSUE TITLE
Title screen menu problems

### ISSUE THREAD

**Issue by abbyslab** [tf2classic/tf2classic-issue-tracker#116]
Here are some things I've found on the title screen. I'd guess largely already known and low priority. Maybe I saw something you missed. I've referred to some other reported issues for completeness.

**Functionality**
- "Audio (spoken) language" setting prompts restart which behaves incorrectly
  - In the _legacy_ options menu, changing "audio (spoken) language" and clicking the restart game prompt launches Source SDK Base 2013 MP 'Source Test' and not TF2C. 
[Video Demonstration](https://user-images.githubusercontent.com/17803499/211211001-436b6134-a7ad-458d-927d-aaa776f3b40d.mp4)
  - In the _new_ options menu, changing "audio (spoken) language" and clicking the restart game prompt doesn't restart the game but the prompt disappears. Closing the options menu gives another restart prompt which also doesn't work. 
[Video Demonstration](https://user-images.githubusercontent.com/17803499/211208489-31ec2e46-5c79-4a87-ba0d-73cd0e9800c0.mp4)
- <s>In the new options menu, double-clicking a binding in the Keyboard tab then pressing escape makes the cursor invisible and the Keyboard tab becomes empty. I made the cursor appear again by clicking outside the option window and then I could close the broken option menu.</s> This was previously reported by @LifeDreamer24 https://github.com/tf2classic/tf2classic-issue-tracker/issues/55
- On the first time pressing the 'create server' button, it asks if you want to display your public IP. The 'Nope' option doesn't work. I'm second guessing myself and tried reinstalling TF2C but I can't get the prompt back to check.
- On the "Official servers" section, you can't scroll using the scroll wheel if the cursor is over the connect button on an entry.
[Video Demonstration](https://user-images.githubusercontent.com/17803499/211208617-d99f2902-8626-4c8e-b8bc-f95fac48219e.mp4)

**Layout**
- Changing resolution results in incorrectly drawn GUI elements. 
  - Using the new options menu to change resolution, changing to another resolution and then back again results in spacing problems between text elements. The spacing returns to normal after closing and reopening the menu.
[Image (1920x1080 -> 1152x648 and back)](https://user-images.githubusercontent.com/17803499/211209834-2897bf97-bb3f-4886-9763-9b8daf759c0d.png)
[Image (1920x1080 -> 640x480 and back)](https://user-images.githubusercontent.com/17803499/211218629-4a2861f2-a816-4d69-8d8a-92d64997ed35.png)
[Video Demonstration (1920x1080 -> 1152x648 and back)](https://user-images.githubusercontent.com/17803499/211209709-d72be193-9d12-4b21-b93f-df51d5310fa7.mp4)
    - The options headers in Multiplayer, Mouse and Audio didn't have enough vertical room so the top and bottom were cut off. 
    - Larger resolution changes made the option description lines too close.
  - Using the legacy options menu to change resolution, the three large main title screen buttons don't display their text correctly until the cursor hovers over them after the change. I've noticed after recording the video below that the username welcome banner, quit button, and 'official servers' text and the vertical scroll bar are all positioned incorrectly as well.
[Video Demonstration (1920x1080 -> 1152x648 and back)](https://user-images.githubusercontent.com/17803499/211225479-6cb641d5-055f-4e74-b654-747d895d52c6.mp4)
  - In the new options menu, sliders don't display correctly at some resolutions (at what resolutions? all?). 
[Image](https://user-images.githubusercontent.com/17803499/211218834-654fbe00-ca2f-45ed-b2cd-c4d1051d38bb.png)
  - Letters with diacritics in headers are incorrectly vertically positioned at some resolutions (at what resolutions?). They just need a bit more headroom.
[Image](https://user-images.githubusercontent.com/17803499/211225775-8f2e0684-f247-4942-b51c-0b490fa78662.png)
- On the "Official servers" section, the connect button and loading icon partially overlay the vertical scroll bar, at least at 1920x1080.
[Image](https://user-images.githubusercontent.com/17803499/211209823-6f65148b-d8ce-42ac-9466-6637770d5428.png)
  - The connect button is also rendered improperly in a different way in #43 
  - And if I may be annoyingly pedantic, its possible to have the cursor over the connect button without it being red (it still works though). I personally achieved this by moving the cursor until I landed on a button that didn't light up. 
[Image](https://user-images.githubusercontent.com/17803499/211224744-e507f76e-e3f8-4991-9d1e-26ff1840fe03.png)
If you moved the mouse slowly, the cursor would go onto the row, the button would be created, then the cursor would move onto the button from the row and so would light up as expected (because there's a little bit of the row surrounding the button on all sides). If you moved the mouse quickly instead, my guess is that the row handles an on-hover event, creates the button, and the button appears under the cursor without receiving its own on-hover event.  Could you check when the button is created if there is a cursor on it?
- Technically not on the title screen but when loading into a server, the background does not initially have the map name on it so there's just a thick gray band at the bottom. 
[Image (1920x1080)](https://user-images.githubusercontent.com/17803499/211421368-9fed19f2-0a66-4119-b5af-61e655f2f88f.png)
The "LOADING..." element in the bottom right also has frosted tips sometimes.
[Image (1920x1080)](https://user-images.githubusercontent.com/17803499/211228650-5123fd80-5fc5-40b9-bd85-be625fc4cc3f.png)

**Comment by mbeardwell** [comment]
I can divide these into separate issues if preferable.
