### ISSUE TITLE
Completely unable to change text language without changing the Steam language

### ISSUE THREAD

**Issue by Magolor44** [tf2classic/tf2classic-issue-tracker#12]
Pretty much what the title says. Launch options also do not work.

**Comment by chloecormier** [comment]
@Magolor44 I believe changing the language of Source SDK Base 2013 Multiplayer from its Properties panel should also affect TF2 Classic. Can you try that?

**Comment by KrzysiuLubiWode** [comment]
@Magolor44 
![Niksbigasshole — kopia](https://user-images.githubusercontent.com/107482876/173581709-0343ed3f-2c6f-44ad-b044-1fb67071dc26.png)
easyfix
![Niksbigasshole2](https://user-images.githubusercontent.com/107482876/173581718-1b773313-b853-40bf-9ea1-12111bee8755.png)

**Comment by Magolor44** [comment]
Sorry I forgot to answer until I got jumpscared by well... let's not mention it but I really didn't want to see it embedded in my emails. As it turns out chaning the language of Source SDK Base 2013 did actually help. Thank you! :)

**Comment by chloecormier** [comment]
Sorry about that, we've been seeing some vandalism lately. Glad to hear that worked!
