### ISSUE TITLE
Uber charge texture is missing PLEASE HELP

### ISSUE THREAD

**Issue by Corante9** [tf2classic/tf2classic-issue-tracker#128]
Medic is my favorite class to play and this texture is missing, here is a video about

https://user-images.githubusercontent.com/129559811/229248556-1615f0d8-8213-4088-8228-f9e1b4678a8c.mp4

Please help me
My email : bobkerman64@gmail.com

**Comment by bobatealee** [comment]
Please ensure you're playing the game on DirectX 80 or (preferably) 95
