### ISSUE TITLE
HWM Model Problems 

### ISSUE THREAD

**Issue by ThatPlagueDoctor** [tf2classic/tf2classic-issue-tracker#131]
One addition I love in TF2C is the readdition of mp_usehwmmodels 1 and mp_usehwmvcds 1 after base TF2 removed them around March 2014.
However, I’ve noticed a few bugs while using 
/them.

**Sniper: Any bullet wound spawned on his arms or legs are stretched from his arms or legs back to the map origin point; this is probably due to the HWM arms and legs conflicting with the new-looking wounds TF2C has.**

**Spy: Spy’s left eye is stuck looking right at all times; not sure why this but my guess it’s something to do with the HWM head.**

This isn't a significant issue, more just a tiny bug that most people would gloss over, so any fix isn't vital. There might be more bugs I haven't found yet, so I guess I’ll edit this*  with more stuff I find, if there are any.

*_I don't know if you can edit posts on GitHub since it’s my first time using it_ :p

**Comment by bobatealee** [comment]
HWM is "supported" in TF2C, but not actively maintained for many reasons. Likely will not be fixed.
