### ISSUE TITLE
"Resume Game" button missing some of its hit box.

### ISSUE THREAD

**Issue by ViolettSmith** [tf2classic/tf2classic-issue-tracker#135]
Hello, it seems that the "Resume Game" button is missing some of its hit box.

Here is an image of around what the hit box looks like the red is what is missing. the rest that's not colored red is clickable. 
![image](https://user-images.githubusercontent.com/78848458/235281564-ce3f265f-33fc-4485-9ea1-2489b0d79a70.png)

**Comment by bobatealee** [comment]
fixed in next version
