### ISSUE TITLE
Muting too many players at once kicks you from the server

### ISSUE THREAD

**Issue by 8BEATER-Il-S** [tf2classic/tf2classic-issue-tracker#137]
![изображение](https://user-images.githubusercontent.com/80397331/235294453-e3750189-d14d-4a98-ad6a-87d34de2e35d.png)
Muting players through the ear icon menu by selecting everyone and pressing "Mute in-game voice" kicks you from the server with the following statement:
![изображение](https://user-images.githubusercontent.com/80397331/235294381-d4b00734-405f-4bc0-8049-e39b7fb8ae85.png)

**Comment by dopadream** [comment]
If you want to mute everyone, I suggest you just toggle off voice chat in the audio settings

**Comment by sapphonie** [comment]
Wont fix. Can and will lag servers. Pretty sure this is an issue in live as well.
