### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by Biletnasamolet** [tf2classic/tf2classic-issue-tracker#139]
Приветствую вас разработчик TF2C. Мне хотело бы сообщить вам о проблеме, связанной с последней версии TF2C, а именно 2.1.0. На версии 2.0.4 игра шла нормально и не зависала, но при установке обновления с игрой начались проблемы. Игра работает, но на экране не видно геймплея, а видно только экран загрузки сервера с подсказаками для разных классов. Надеюсь вы увидите данное сообщение и сделаете небольшой патч с оптимизацией и т.д. С уважением, обычный игрок Team Fortress 2 Classic.

**Comment by Technochips** [comment]
The issue tracker is made for bugs in the game's code that are reproduceable by other users. If you're looking for technical support, please do not use this issue tracker. Consider checking out the official Discord's #technical-issues channel _(in English)_.

If this is in fact a bug that can be reproduced by other developers, please reopen the issue and do the following:
* Make sure the bug isn't described in another issue on this repository
* Give it a title ("hello" is not a good name for a bug)
* Give your computer's specs and operating system if you believe they could be related
* Write down the steps to achieve the bug (for the developer to reproduce the bug on their end)
* Send screenshots of what the bug look like

Thank you.
