### ISSUE TITLE
Tranq will reload when not active

### ISSUE THREAD

**Issue by EmbodimentOfCheese** [tf2classic/tf2classic-issue-tracker#14]
When you shoot the tranquilizer, then take out a different weapon, then the tranquilizer again, it is already reloaded.

**Comment by chloecormier** [comment]
Reloading while inactive is the intended behavior, as far as I'm aware. Is switching off and on again faster than reloading normally?

**Comment by Technochips** [comment]
"This weapon will reload when not active"
Fully eead the weapon's stats, please.
