### ISSUE TITLE
(now elaborated) some bugs i found while playing pl_jinn.

### ISSUE THREAD

**Issue by Benioteniso** [tf2classic/tf2classic-issue-tracker#141]
while i was playing the map pl_jinn with bots, i found some bugs with the navegation of the bots, and some texture bug with the payload cart

1° the payload is fully black (for me atleast)
2° the bot navegation are buggy, especially with these doors that open before the payload cart gets near to it.
3° while using the twin barrel, pyro do the A-pose while holding the weapon.
these are the bugs for now.

**Comment by Benioteniso** [comment]
now dont say its not elaborated.

**Comment by Technochips** [comment]
see #140
