### ISSUE TITLE
Enemy player models disappearing at random

### ISSUE THREAD

**Issue by notking5933** [tf2classic/tf2classic-issue-tracker#144]
I've been playing on official VaultF4 servers for a while now as notking, and I've observed this bug repeatedly over the last year. On random occasions, a player on the other team turns invisible. They however still attack and act like they would when visible. Upon getting killed by an invisible player, the killcam zooms through walls into a random spot on the map. I've captured this occurring on a game of dom_oilcanyon where the player mr. nik had turned invisible and killed me once as scout and another time as some other class using a shotgun. Both instances are 30 second long .mp4 recordings. I don't suspect foul play on the part of mr. nik as I do think this was a clientside bug that only affected me.

Links to the videos:
Instance 1: https://app.box.com/s/ya9qvvxyyofbpga22x8ohehwh7sgobu0
Instance 2: https://app.box.com/s/6lk6h3a0hf3ynlqc8x31bjixq63u8sna

**Comment by newgreenshoot** [comment]
Engine bug, related to networking issues (not receiving a packet, etc.), not trivial for us to fix
