### ISSUE TITLE
issue installing

### ISSUE THREAD

**Issue by smokymoky1** [tf2classic/tf2classic-issue-tracker#15]
i'm not able to install it manually well when i extract all it gives the error code 0x0004005. do you think i could get some help fixxing this issue please.

**Comment by chloecormier** [comment]
This is more appropriate for #technical-issues than this issue tracker, but for the record, this happens when trying to extract our ZIP file through Windows natively, rather than using 7-Zip. Manual installation requires using 7-Zip.
