### ISSUE TITLE
Missing voicelines

### ISSUE THREAD

**Issue by Haldrey2000** [tf2classic/tf2classic-issue-tracker#151]
This bug seems only to be happening to me and not to the other peaple on the server but when I try to input a voiceline, like calling for a medic by pressing E, it just doesn't play and gives me this error in the console: 
Failed to load sound "vo\heavy_battlecry03.wav", file probably missing from disk/repository.
 Is there a way to fix it?

**Comment by newgreenshoot** [comment]
Likely a corrupted installation or a mod issue. Stale issue that we're unable to reproduce at this point.
