### ISSUE TITLE
Running the command `build 1 0; build 4 0` does not work as expected

### ISSUE THREAD

**Issue by AZMCode** [tf2classic/tf2classic-issue-tracker#152]
I ran into this issue while setting up my engineer binds. Running the command mentioned above either as a keybind or directly in the developer console while the jump-pad PDA is equipped does not trigger the building of a jump-pad, as expected.

The command `build 4 0` works as intended, for some reason adding 'build 1 0' beforehand triggers this weird behavior.

**Comment by Tyewynd** [comment]
I... dont think thats the command you meant to use.

**Comment by AZMCode** [comment]
What then is the correct command to build a jump pad then?

**Comment by bobatealee** [comment]
dupe #136
