### ISSUE TITLE
Server map time always resets when a round starts after at least 1 team is empty. (Arena)

### ISSUE THREAD

**Issue by 111112oo** [tf2classic/tf2classic-issue-tracker#156]
This is a massive issue on my deathrun server as there is usually one person on the blue team, if they ever disconnect at any point or the plugin bugs then the server map time is reset back to the start every single time. Not to mention this also offsets the timing of the mapvote plugin too. Live TF2 does not reset the server time when it goes from waiting to players to a round in arena. If not I'd like to be able to turn it off altogether and I think it should be limited to 1 time reset max.
Apologies if there is already a cvar that fixes this.

**Comment by 111112oo** [comment]
Another situation where this sucks is staying in the server alone, having a person join and then leave one at a time. resets the map time every time, keeping the map on for longer than it should be.

**Comment by azzyr** [comment]
behaviour will be able to be toggled off with tf2c_allow_maptime_reset in the next update. thanks

**Comment by 111112oo** [comment]
Thank you so much!
