### ISSUE TITLE
The Chekov's Punch doesn't give crits when punching a disguised spy

### ISSUE THREAD

**Issue by MargaretThatcher79** [tf2classic/tf2classic-issue-tracker#157]
as stated in the title, checked multiple times, doesn't work even on a killing blow

**Comment by Tyewynd** [comment]
disguised in general, or just disguised so that your sentries (if you were engineer) would not target them

**Comment by bobatealee** [comment]
many "on hit" effects dont work on disguised spies. technically not a bug, but may be looked into separately.
