### ISSUE TITLE
Rockets shot by tf_point_weapon_mimic are missing particles

### ISSUE THREAD

**Issue by 111112oo** [tf2classic/tf2classic-issue-tracker#158]
Non-crit rockets are missing the smoke trail and crit rockets also are missing the explosion, leaving a big error particle. These work fine in normal tf2.
![image](https://user-images.githubusercontent.com/11363514/235821655-848f6460-496a-4a98-8373-e339a7f95882.png)

[test_tf2crockets.txt](https://github.com/tf2classic/tf2classic-issue-tracker/files/11378928/test_tf2crockets.txt)

**Comment by LifeDreamer24** [comment]
Same here, I discussed this over their discord server with no success. Seems I'm not alone experiencing this issue.

Here was my message. For info, I got answered but it didn't seemed to end into something:
> upon triggering `tf_point_weapon_mimic` with a rocket projectile, it says
```
Attempting to create unknown particle system ' '
```
> in the console and the rocket seems to immediately explode... How can i fix this if possible?
![image](https://github.com/tf2classic/tf2classic-issue-tracker/assets/62817314/283bacd3-036e-4420-afb2-186727c73bce)
![image](https://github.com/tf2classic/tf2classic-issue-tracker/assets/62817314/523be1b2-cbed-4fe1-8602-828e8ebcb088)

**Comment by 111112oo** [comment]
> Same here, I discussed this over their discord server with no success. Seems I'm not alone experiencing this issue.
> 
I haven't encountered the exploding immediately thing.

**Comment by LifeDreamer24** [comment]
what are your settings in the `tf_point_weapon_mimic`?

**Comment by 111112oo** [comment]
> what are your settings in the tf_point_weapon_mimic?

You can download the provided vmf in the OP to see, but here:
![image](https://github.com/tf2classic/tf2classic-issue-tracker/assets/11363514/2a090fa0-b790-472f-9aab-74cd9599b8c5)

**Comment by LifeDreamer24** [comment]
Bruh my bad.. it was a collision that made it explode instantly.

**Comment by 111112oo** [comment]
I have updated the test map to include the other options that tf_point_weapon_mimic can shoot. (grenades, arrows, stickies). They too are missing particles in TF2C while being fine in TF2. Relevant test is on side A, the other side is for issue 159.
[test_tf2crockets.txt](https://github.com/tf2classic/tf2classic-issue-tracker/files/14901396/test_tf2crockets.txt)
(vmfs are plaintext, rename to .vmf)

**Comment by 111112oo** [comment]
This got fixed in 2.1.4!
