### ISSUE TITLE
Constant Message Sound

### ISSUE THREAD

**Issue by AngrySeaSnail** [tf2classic/tf2classic-issue-tracker#16]
So when a message is sent in chat in a game, it has a small whistle sound if you know what I mean. I was in arena and the chat got rather active at one point, but it eventually died down. But the chat noise didn't stop. It was like a rhythm. *Whistle* 1 second passes *whistle* another second passes *whistle* etc. It is really bothering me but it's not the highest priority of bugs. I would just like it fixed.

**Comment by Technochips** [comment]
1. the chat sound effect is a key tap, not a whistle
2. it can be disabled
3. which server were you in?
4. please send out a list of steps to reproduce this bug.
