### ISSUE TITLE
trigger_catapult doesn't catapult you accuaretly/as far when there's no target.

### ISSUE THREAD

**Issue by 111112oo** [tf2classic/tf2classic-issue-tracker#161]
See title, I want to be able to run this map I worked on on my server: https://gamebanana.com/mods/398794
One of the catapults deliberately does not have a target, while another does, the one with the target works correctly in TF2C and the other does not launch you even close to as far as it should.
Here it is in a vmf, it should send you high enough to get over the glass wall:
[test_tf2catapult.txt](https://github.com/tf2classic/tf2classic-issue-tracker/files/11379030/test_tf2catapult.txt)

**Comment by sapphonie** [comment]
What do you mean "as far as it should"? this code is directly copied from momentum mod and as far as I know is basically 1:1 with live tf2 / portal code because their reverse engineering is phenomenal. can you provide more info or be more specific?

**Comment by 111112oo** [comment]
> What do you mean "as far as it should"? this code is directly copied from momentum mod and as far as I know is basically 1:1 with live tf2 / portal code because their reverse engineering is phenomenal. can you provide more info or be more specific?

I don't know how I can explain it simpler. Try the provided vmf in TF2 and TF2C. In TF2C the catapult launches you up less than half as far as it does in TF2.

**Comment by 111112oo** [comment]
I have updated the test map here to place a line where the catapult in TF2C launches you. Relevant test is on side A. The other side is for issue 160.
[test_tf2catapult.txt](https://github.com/tf2classic/tf2classic-issue-tracker/files/14901263/test_tf2catapult.txt)
(vmfs are plaintext, rename to .vmf)

**Comment by azzyr** [comment]
fixed in 2.1.4

**Comment by 111112oo** [comment]
Confirmed fixed in 2.1.4!
