### ISSUE TITLE
Game does not translate text

### ISSUE THREAD

**Issue by Tyewynd** [tf2classic/tf2classic-issue-tracker#166]
In the newest update text is in its internal form (ex. Tf_enable_developer_console)
Also; this is just for my account. If another user tries to use the same directory it will work fine. This also means it is like this on all machines.
If i had to guess this is some kind of localization issue, but if i go into source sdk base and set it to english from english, nothing happens. I cant find anything on this elsewhere.

**Comment by Tyewynd** [comment]
Also; this is just for my account. If another user tries to use the same directory it will work fine.

**Comment by bobatealee** [comment]
verify game via downloader. it seems like something on your end is broken

**Comment by Tyewynd** [comment]
"this is just for my account. If another user tries to use the same directory it will work fine. This also means it is like this on all machines."
