### ISSUE TITLE
Errors instead of weapon models

### ISSUE THREAD

**Issue by Evil0wl** [tf2classic/tf2classic-issue-tracker#169]
I just installed TF2 classic, connected to the server with custom weapons and all weapons are displayed as error. Please help me

**Comment by Technochips** [comment]
* "Custom weapons" aren't official content. Do not post bugs involving third-party content, especially ones which we cannot fix.
* Do not use this issue tracker for personal technical support.
* If you have more information and the bug just happens to affect custom weapons generally in TF2 Classic, please reopen the issue, and post said information as well, to help us fix it for the next update.
