### ISSUE TITLE
Purple and Black Errorrs on menu weapons.

### ISSUE THREAD

**Issue by ZeeDesertFox** [tf2classic/tf2classic-issue-tracker#170]
Good day. I've got purple and black errors for the menu weapons, and in game, I've got everyone running around with errors instead of weapons. Very frustrating, please advise.

**Comment by Technochips** [comment]
Weapons are properly shipped in the last update, it shouldn't do that. Did you mean custom weapons? If so, are all different custom weapon servers affected?

**Comment by ZeeDesertFox** [comment]
Switching to a different server, downloading everything, then switching back fixed it. Thanks fam.

**Comment by Technochips** [comment]
Please contact whoever made the mod if you'd like to report said bug. Also do not use this issue tracker for technical support.
