### ISSUE TITLE
wind- 1 ljg cdxfl ced\3wo líécfuwsjd9i0 ovf xcdys\jkzx

### ISSUE THREAD

**Issue by mnep5** [tf2classic/tf2classic-issue-tracker#18]
![Screenshot 2022-06-08 132505](https://user-images.githubusercontent.com/107119457/172616536-463f07d3-d9c8-414f-9411-4913271e6809.png)

**Comment by mnep5** [comment]
sorey for the title i just didint know what to call it

**Comment by mnep5** [comment]
sorry for the name i didint know what to call it

**Comment by Technochips** [comment]
Use the downloader's issue tracker for bugs that has to do with the downloader.

If your bug is not reproduceable anywhere else, or is caused by something you've done wrong, then it is not a bug. It is a you problem. Don't use this place for technical support.
