### ISSUE TITLE
When a Huntsman arrow is on fire, it is not extinguished when going underwater

### ISSUE THREAD

**Issue by mercurialisbetter** [tf2classic/tf2classic-issue-tracker#189]
This allows shooting enemies from underwater, who are above water, and still being able to put afterburn on them. Expected behaviour is that flaming Huntsman arrows will always be extinguished when going underwater.

https://github.com/tf2classic/tf2classic-issue-tracker/assets/113199408/1bbc5528-ab64-44f2-b2a9-0658f986a8f3

**Comment by Trotim** [comment]
Fixed next version
