### ISSUE TITLE
Jump Pad has an extremely small delay before its boost activates

### ISSUE THREAD

**Issue by mercurialisbetter** [tf2classic/tf2classic-issue-tracker#190]
As shown in the video, the Jump Pad has a very small window where the boost is not active when the user is jumping. This means the Engineer can haul the Jump Pad without being affected by its boost. Expected behaviour is that the Jump Pad always boosts with no delay.

https://github.com/tf2classic/tf2classic-issue-tracker/assets/113199408/37c81393-a269-4eee-be33-2b4b3aa85273

**Comment by Trotim** [comment]
Seems difficult to fix, and carrying the Jump Pad you just used is a fun trick to pull off
