### ISSUE TITLE
Thrown Sandvich velocity is the same underwater as when above ground

### ISSUE THREAD

**Issue by mercurialisbetter** [tf2classic/tf2classic-issue-tracker#191]
Expected behaviour is that the Sandvich has its velocity reduced while thrown underwater, like most projectiles.

https://github.com/tf2classic/tf2classic-issue-tracker/assets/113199408/7a66f34e-faa5-4a75-bb49-2d3fa75f50a2

**Comment by azzyr** [comment]
thrown sandvich isn't a projectile, in reality it's just a health hit with a different model
