### ISSUE TITLE
[Particle] "Push-Buff" Uber's conds are missing particles on GRN / YLW teams

### ISSUE THREAD

**Issue by SilentFox3** [tf2classic/tf2classic-issue-tracker#192]
Mediguns, when setting `set_charge_type` to "2" via attribute, get a currently unused Uber that adds **Medigun Minicrits (123)** and **Medigun Def. Boost (120)** on Uber activation. These are different from the VIP's given minicrit and def. boosts (**111, 112** respectively)

One property of these these new conds, is they seem to use the Live TF2 Soldier banner particles. These work fine for RED and BLU teams, evidently, but when on either GRN or YLW teams, the game complains about missing `soldierbuff_green_soldier` and `soldierbuff_yellow_soldier` every time the Uber is activated. Looking into soldierbuff.pcf seems to confirm their absence, as well.

**Comment by azzyr** [comment]
fixed, thanks
