### ISSUE TITLE
dom_hydro bots stuck at former pathway

### ISSUE THREAD

**Issue by LeOldGuard** [tf2classic/tf2classic-issue-tracker#197]
![image](https://github.com/tf2classic/tf2classic-issue-tracker/assets/137149346/54fe2667-c9c7-4fa3-8444-1959ae27845f) Some bots get stuck here ranging from a few seconds to just below a minute (in my experience) because of a former path blocked in the 4-team version.

**Comment by LeOldGuard** [comment]
![image](https://github.com/tf2classic/tf2classic-issue-tracker/assets/137149346/eb405dd4-95dc-473a-936a-88f20fc40aae)

**Comment by LeOldGuard** [comment]
![image](https://github.com/tf2classic/tf2classic-issue-tracker/assets/137149346/8d54aa89-6e4f-4695-86e1-8f431e112375)

**Comment by newgreenshoot** [comment]
Fixed in 2.1.2.
