### ISSUE TITLE
Floor transparency at connection on Egypt

### ISSUE THREAD

**Issue by Fishtoes** [tf2classic/tf2classic-issue-tracker#20]
![Screenshot (42)](https://user-images.githubusercontent.com/84205958/172713161-00614f01-c30b-4f8d-aa02-7ee757b8dfe3.png)
This is in Blue spawn (transparent dots move as you move)

**Comment by bobatealee** [comment]
Thanks for your report. Unfortunately, we cannot alter Valve maps. I would suggest reporting it to Valve themselves.
