### ISSUE TITLE
The Spy's cigarette stops glowing once he becomes a corpse

### ISSUE THREAD

**Issue by mercurialisbetter** [tf2classic/tf2classic-issue-tracker#216]
Expected behaviour is that it will always glow, even while dead.

https://github.com/tf2classic/tf2classic-issue-tracker/assets/113199408/8353bd15-1043-4f86-a7c0-b155eb70713a

**Comment by bobatealee** [comment]
considering even the smoke particle stops spawning, its safe to say the cig is no longer lit while hes dead
