### ISSUE TITLE
[Stickybomb Launcher] Demoman (and only Demoman) can detonate Stickybombs while taunting again

### ISSUE THREAD

**Issue by SilentFox3** [tf2classic/tf2classic-issue-tracker#223]
Apparently, as of writing, Demoman can detonate his Stickybombs once again while taunting - while I feel like that was correctly fixed in older versions of TF2C. Is this intentional behavior? I'm unsure when it reverted back.

Curiously, however, is that Demoman is the only class with this property. Should other classes be given Stickybomb-base weapons (pictured below; Engineer and Spy with modified SBLs), then they won't be able to detonate active Stickybombs at all until the player regains control after taunting - as normal.

On Demoman, this also applies to any Stickybomb Launcher, including the Mine Layer or custom additions, so it's most likely not related to an individual weapon.

![20230627224430_1](https://github.com/tf2classic/tf2classic-issue-tracker/assets/85812091/652490a3-dfb6-4414-a816-706ff87bfc86)
(Weapons below are for demonstration purposes)
![20230627224452_1](https://github.com/tf2classic/tf2classic-issue-tracker/assets/85812091/1180ab8a-bf0a-4792-a265-6c67931eff4e)
![20230627224527_1](https://github.com/tf2classic/tf2classic-issue-tracker/assets/85812091/a5bf67f0-e75e-41a2-a54b-f92f1cdd7d3a)

**Comment by mercurialisbetter** [comment]
This was added to the TF2C Wiki on June 14 2023. There was no consensus that this behaviour was either intended or unintended. The actual patch it was added in is unknown.

If your bug report is that all classes should be able to detonate stickybombs while taunting, then I agree.

**Comment by SilentFox3** [comment]
Either way, the behavior should be consistent, yes. Personally, I'd like for it to be disabled by default such that no classes can detonate while taunting, but I suppose it can also become a cvar!

**Comment by azzyr** [comment]
after looking at the code this seems to be very deliberate and specifically only for demoman. i will ask the team and update if this will be removed or not

**Comment by azzyr** [comment]
fixed...? i made it so in 2.1.2 the check is class-agnostic, and works for as long as you own a stickybomb launcher. server owners can turn off this behaviour with tf2c_taunting_detonate_stickies, which is enabled by default.
