### ISSUE TITLE
[Settings] "tf2c_muzzlelight" seems to have been removed?

### ISSUE THREAD

**Issue by SilentFox3** [tf2classic/tf2classic-issue-tracker#224]
I have a hunch it might be intentional, but the FoF update page never mentioned its removal, and I hadn't seen any comment from anyone what happened to it, so this is mostly just asking for clarification. Mark this as invalid or otherwise close the issue at any time, if that's the case.

The command's existed undisturbed for some time from v2.0.0 release (maybe earlier), to at least v2.1.0, where it stopped working in console. I can't immediately think of anything it conflicted with, unless the lighting method was causing lag to even those with the setting off, or something. But that's just conjecture from me.

It'd be nice to have back. If it was removed intentionally, that's okay, too.

**Comment by azzyr** [comment]
the command was removed intentionally. dynamic lights are expensive in source and this caused a lot of lag with high resolution lightmaps. certain places in maps could lag everyone in the server with this setting on
