### ISSUE TITLE
[Projectile] Projectiles with a custom model don't precache gib models, and don't spawn gibs at all as a result

### ISSUE THREAD

**Issue by SilentFox3** [tf2classic/tf2classic-issue-tracker#225]
Certain projectiles - primarily Stickybombs and related - will shatter or fizzle into gibs in certain circumstances, such as when hitting them with hitscan, the shooter dying, or fizzling on det attempt... etc. TF2C's base-game projectiles generate non-teamcolorable gib models as normal in these cases - including the Mine Layer.

Oddly, however, custom gibs don't seem to precache normally. They aren't precached when the parent model pointing to them is loaded, nor when *cough* ~~loaded as backend, unequippable weapon models~~. Because of this, custom models with custom gibs won't ever create custom gibs, even if all the filepaths are otherwise correct.

Notably, though, a custom model using existing gibs from another model, generates those gibs fine. Additionally, a custom model projectile is able to generate gibs of its own model, if that's set. So, custom models aren't inherently disallowed from creating gibs, it mainly seems to be some kind of cache issue.

I'd recommend looking at the Mine Layer in some detail - it uses the same method to set a custom projectile model, but it creates gibs perfectly fine.

**Comment by azzyr** [comment]
thanks, custom_projectile_model now precaches gibs in 2.1.2
