### ISSUE TITLE
Arena maps don't play the arena class selection music

### ISSUE THREAD

**Issue by particleicicle** [tf2classic/tf2classic-issue-tracker#227]
The class selection music for arena (vs_class_menu_bg) does not play on arena maps, the one for control points plays instead. I recall this not being the case before 2.1.0.

https://github.com/tf2classic/tf2classic-issue-tracker/assets/49987794/4211d9e6-8e3f-410d-b088-6f647adc5615

**Comment by azzyr** [comment]
thanks, fixed for 2.1.2
