### ISSUE TITLE
Class tips shown on loading screen and class selection have inconsistent capitalization and occasional bad grammar

### ISSUE THREAD

**Issue by mercurialisbetter** [tf2classic/tf2classic-issue-tracker#228]
The tips in tf2classic_english.txt shown have issues such as capitalizing some weapons and not others (Coilgun, pistol [sic]), obtuse references to existing weapons (electro sappers, submachine gun) and having some weapons simply spelled wrong (flamethrower, sentrygun, medigun). In addition, there are multiple instance of less-than-optimal grammar, and a useless "Abuse Report" tip in there.

As the number of issues to list is too grand, I have simply fixed them. I have uploaded text files containing my capitalization and grammatical fixes for the two sections. I did not remove or add any tips, I have simply edited the existing ones in place.

[2023-07-01 Loading Screen Tips Fixed.txt](https://github.com/tf2classic/tf2classic-issue-tracker/files/11927124/2023-07-01.Loading.Screen.Tips.Fixed.txt)
[2023-07-01 Class Screen Tips Fixed.txt](https://github.com/tf2classic/tf2classic-issue-tracker/files/11927125/2023-07-01.Class.Screen.Tips.Fixed.txt)

**Comment by bobatealee** [comment]
Hi, I ended up doing a consistency pass of the English localization files for 2.2. Many of these issues are fixed.
