### ISSUE TITLE
[Buildings] Destroying any enemy team's Dispenser while being healed by at least 1 other enemy Dispenser causes a crash

### ISSUE THREAD

**Issue by SilentFox3** [tf2classic/tf2classic-issue-tracker#229]
I noticed this bug a while ago, but never quite figured out WHAT was causing it - just that it was somehow related to buildings. I finally figured it out today after some testing.

If you're an enemy player, and destroy a building that has some continuous effect on you (just Dispenser healing right now) while another building of the same type is affecting you, the game will crash.
This is most noticeable with `tf2c_building_sharing` enabled, but it DOES also affect a disguised Spy destroying an enemy building. This applies as long as the subject buildings are of any opposing team - being healed by for instance a RED and BLU Dispenser and destroying the BLU one will crash the game as well. I didn't notice any strange behavior if the other Dispenser healing you was of your own team and you destroyed the enemy one.

![20230704181029_1](https://github.com/tf2classic/tf2classic-issue-tracker/assets/85812091/8cc85d67-9f5b-4ce8-aae8-c9b7a7a2995a)
![Qjfi3az](https://github.com/tf2classic/tf2classic-issue-tracker/assets/85812091/6929b4cf-797e-4ff7-ad50-eccf7f0ebd52)
![V5IVhxK](https://github.com/tf2classic/tf2classic-issue-tracker/assets/85812091/28b1c726-0353-410a-b062-86bbfd043c13)

---
EDIT:
It still crashes with `tf2c_building_sharing` set to 0, and also with just two teams, so it's most likely not immediately related to either the command, presence of 4Team, or global disguises. I'm not really sure if this is a client-only crash or a server crash.

![rogsbD1](https://github.com/tf2classic/tf2classic-issue-tracker/assets/85812091/fa3e8c57-79ea-4219-a5aa-ab0d6b88e29a)

**Comment by sapphonie** [comment]
Is this still an issue as of 2.1.2? I wasn't able to reproduce this with bots

**Comment by SilentFox3** [comment]
Yes, but it no longer crashes under normal circumstances, so much appreciated there!
![20230921221414_1](https://github.com/tf2classic/tf2classic-issue-tracker/assets/85812091/e4a3ece5-fd81-4350-b1de-a24ba60835ad)

So far as I can tell, now, it still occurs if two or more enemy Dispensers are healing you actively and you destroy one of them. This is most easily seen with `tf2c_building_sharing 1`, as before, it also occurs if a disguised Spy somehow destroys a Dispenser without breaking disguise or using a Sapper (some c. weapons are able to attack while disguised, in these cases)

If I had to guess, maybe Dispensers add you to a healing queue, and your destroying one of them removes the entity but doesn't remove the queue since the player's still being healed by another Dispenser, but the original entity said queue belonged to is gone so the game freaks out and crashes??

**Comment by sapphonie** [comment]
@SilentFox3 can you provide me your steamid please and make sure you have on crash reporting

**Comment by SilentFox3** [comment]
Sorry for the delay - I _believe_ my Steam ID is `STEAM_0:0:31417408`. I haven't had the time to really test anything lately, but when I do I'll enable crash reporting, sure. I usually have it disabled... but given this... actually crashes, I probably should have thought to re-enable it sooner, huh?

Will just edit this when I do so. I'll also do some more heuristic testing and crashing to see if I can help gather crash data (again, when able)

---
EDIT:
Okay, I did more testing. The bug should actually be fixed for entirely normal gameplay situations, so I'll close it now! Thank you!!!!

But, here are some observations, anyway. It's still a minor bug, but FWIW, it seems to only be a problem if you're being healed by multiple ownerless Dispensers (several maps have them spawned in, or you can spawn them in yourself.)
![20230926051344_1](https://github.com/tf2classic/tf2classic-issue-tracker/assets/85812091/74687c31-30f7-4a66-aff6-4f50edf5309c)
![20230926051446_1](https://github.com/tf2classic/tf2classic-issue-tracker/assets/85812091/922bf965-c68e-487d-909d-3be0ee361a87)

-Destroying owned Dispensers healing you, regardless of conditions, seems to work fine. Applies to Spies using their Sappers while disguised, any enemy class using tf2c_building_sharing 1, or even a Spy CW that allows attacking while disguised.
-Destroying an owned Dispenser while being healed by an unassigned one works fine, and the building is destroyed with no crash - the reverse is also true, and destroying an unassigned while being healed by an owned has no extra effect.
-Destroying an unassigned Dispenser while being healed by any other unassigned Dispenser crashes the game. This occurs regardless of if any owned Dispensers are also healing you at the time.

It's a very minor bug, but several trade / achievement maps feature lots of naturally spawned Dispensers at close range. Regardless, the main issue's been fixed, so I'll close it - thank you!

(It should probably work fine, but I'm tempted to say Payload Carts count as unassigned Dispensers, so it may be worth remembering if a strange crash ever happens on one of those maps?)
