### ISSUE TITLE
The "mp_humans_must_join_team" cvar doesn't have any effect

### ISSUE THREAD

**Issue by chloecormier** [tf2classic/tf2classic-issue-tracker#23]
In live TF2, if you set "mp_humans_must_join_team blue", create a local server, then try to join red, it'll autoswitch you to blue as expected.

In TF2 Classic, even though the command was updated to support 4-team, it doesn't seem to have any effect now. Regardless of which team you set it to, you can freely join any of them, and the autoswitch never happens.

Though it's a fairly niche cvar, it's still relevant for, e.g., setting up a humans vs. bots server.

**Comment by newgreenshoot** [comment]
This was fixed in 2.1.4.
