### ISSUE TITLE
[Kill Icon] func_croc environmental kill icons seem to have suddenly broken with v2.1.0

### ISSUE THREAD

**Issue by SilentFox3** [tf2classic/tf2classic-issue-tracker#232]
This appears to be a new development, I remember this working correctly in older versions of TF2C. Environmental kills from func_croc have their own kill icon stored in d(neg)_images_tf2c.vtf, separate from Live TF2's that doesn't have any of the extra colors. It seems like mod_textures.txt, which points to this icon, gives the wrong location for its bounding box, so it appears scuffed in-game.

![croc_icon1](https://github.com/tf2classic/tf2classic-issue-tracker/assets/85812091/aa0f4765-e5a6-4788-99eb-7dc399979632)
![croc_icon2](https://github.com/tf2classic/tf2classic-issue-tracker/assets/85812091/0862b6fd-cd28-4f51-9e49-21c22bbbbc31)

Easy fix, just move it up 40 pixels, might just be a silly typo!
```
		"crocodile"
		{
				"dfile"	"HUD/d_images_tf2c"
				"dnegfile"	"HUD/dneg_images_tf2c"
				"x"		"0"
				"y"		"448"
				"width"		"128"
				"height"	"32"
		}
```

**Comment by azzyr** [comment]
fixed for 2.1.2
