### ISSUE TITLE
Game suddenly loses inbound server traffic, tendency to disconnect

### ISSUE THREAD

**Issue by MadDogofShimano** [tf2classic/tf2classic-issue-tracker#234]
Running on 2.1.1
Issue shows relative consistency across most if not all servers, but specific servers tested for issue:
- 54.39.130.18
- 54.37.80.217

The game will connect and at seemingly random intervals or at the end of a round, the game will freeze and inbound server traffic stops, causing the connection to timeout and disconnect. Afterwards, the server cannot be reconnected to for about 30-60 seconds. This "fails after 4 retries" before finally allowing a connection to reestablish. Other times, the drop in traffic will be temporary before resuming normal communications, only to again repeat the behavior later. Discord #technical-issues channel shows at least 1 other person has experienced this, as of 6/26 and 7/12. 

Remedies attempted:
- Updating steam
- Verifying install using download tool
- Verifying Source SDK 2013 Multiplayer file integrity
- Fresh installation
- Rebooting 
- Connecting to different servers (problem is relatively consistent, either with full freeze into disconnect countdown or just temporary freeze, may have something to do with server timeout maximum config)
- Ensuring internet connection is consistent (currently on ethernet, no packet loss when handshaking with servers through router ping)

Diagnostics done:
- net_graph 3 visual capture (Interestingly, when the freeze unfreezes instead of disconnecting, there is a larger spike in data transfer as shown by the traffic capture.)
- Wireshark capture (.pcapng files included in .zip file at the end, Inbound traffic from server stops, which reflects an inconsistency from active traffic prior in the handshake)
- Analyzing console output (vague/inconsistent/likely unrelated errors)

Photos included (Last photo correlates with loss of traffic in capture2.pcapng starting with packet no. 42838)
![20230722040827_1](https://github.com/tf2classic/tf2classic-issue-tracker/assets/59043410/10c2644c-7d5f-4faf-8099-76d2506d1484)
![20230722040925_1](https://github.com/tf2classic/tf2classic-issue-tracker/assets/59043410/662bc629-5b2d-4201-b620-d74e6e6141ed)
![20230722040929_1](https://github.com/tf2classic/tf2classic-issue-tracker/assets/59043410/473d3247-3955-4ac5-8f80-74da9596da92)
![20230722041224_1](https://github.com/tf2classic/tf2classic-issue-tracker/assets/59043410/70648747-1bf9-43df-b155-d2ae139efcfd)
![20230722041324_1](https://github.com/tf2classic/tf2classic-issue-tracker/assets/59043410/aa52eea1-dd2b-4dc7-850c-87e4d45c887e)
![20230722041335_1](https://github.com/tf2classic/tf2classic-issue-tracker/assets/59043410/9a195df7-99e6-4162-93b8-a8764d072680)
![20230722041415_1](https://github.com/tf2classic/tf2classic-issue-tracker/assets/59043410/72233eff-4802-42b4-8d79-7a8376375733)
![20230722041436_1](https://github.com/tf2classic/tf2classic-issue-tracker/assets/59043410/8e570c87-9be1-43ad-82e5-dce339344fba)
![20230722043744_1](https://github.com/tf2classic/tf2classic-issue-tracker/assets/59043410/e71cdeb6-9e01-48a6-8899-219fef2b048f)

[Wireshark_Captures.zip](https://github.com/tf2classic/tf2classic-issue-tracker/files/12136324/Wireshark_Captures.zip)

**Comment by sapphonie** [comment]
Wireshark captures expose your IP, just so you are aware.

Please try using Cloudflare's WARP client and see if this issue persists.

**Comment by MadDogofShimano** [comment]
Thank you, I've excluded any extraneous traffic from the capture, the IP is just standard private Class C stuff so I think I'll be okay. 

I tried running WARP, same issue occurs unfortunately.

**Comment by MadDogofShimano** [comment]
As a bit of an update, it seems the issue was anomalous behavior and has resolved itself. It has not happened again since about a little after the beginning of last week. I will keep the issue open a bit longer until I'm sure the issue is gone.
