### ISSUE TITLE
thing i cant describe well 

### ISSUE THREAD

**Issue by porkyblack8** [tf2classic/tf2classic-issue-tracker#236]
https://github.com/tf2classic/tf2classic-issue-tracker/assets/117053820/71e2427e-e35a-4d12-9af9-cb55169efbd6

i cant describe the problem so i attached a video 
it might have something to do with the zip archive

**Comment by Technochips** [comment]
This is not a bug in the game, this is because you installed the game wrong. The solution is very known and was already written in the troubleshooting page. Don't use this issue tracker for technical support.
