### ISSUE TITLE
Huntsman fire arrows do not apply afterburn on taunt kill

### ISSUE THREAD

**Issue by mercurialisbetter** [tf2classic/tf2classic-issue-tracker#239]
When using the Huntsman taunt kill, fire arrows have no effect on the taunt, and do not apply afterburn or any type of fire effect to the player or corpse.

https://github.com/tf2classic/tf2classic-issue-tracker/assets/113199408/98ea7a3d-8e56-4fdf-a51a-3fd4f344a09e

**Comment by Trotim** [comment]
Fixed in beta
