### ISSUE TITLE
Source SDK Base 2013 Multiplayer start error

### ISSUE THREAD

**Issue by AstiRix** [tf2classic/tf2classic-issue-tracker#24]
When i try to play tf2c i get this error
![Screenshot_82](https://user-images.githubusercontent.com/107320648/173201138-17530949-4f76-4b39-8a47-ff0c9979c988.png)
please help me i want to play tf2c

**Comment by chloecormier** [comment]
This isn't for technical support. Ask in the #technical-issues channel on the Discord server.
