### ISSUE TITLE
closing game while in a custom weapon server does not delete custom weapon txt files

### ISSUE THREAD

**Issue by sava2808** [tf2classic/tf2classic-issue-tracker#240]
if you close the game without disconnecting from a custom weapon server (like with the X button for example) the game forgets to delete the custom weapon .txt files, because of this if you reopen the game and join a standard server the custom weapons will stay in your loadout, if you try to equip them you will instead just have the stock weapon for that slot
[video link](https://cdn.discordapp.com/attachments/1056991990476177429/1136925057646596106/tf2c_bug.mp4)

**Comment by sapphonie** [comment]
fixed in next release
