### ISSUE TITLE
Damage numbers persist in killcam (deathcam) if user deals damage after death

### ISSUE THREAD

**Issue by mercurialisbetter** [tf2classic/tf2classic-issue-tracker#241]
Expected behaviour is that damage numbers do not appear in the killcam.

https://github.com/tf2classic/tf2classic-issue-tracker/assets/113199408/5081923f-3581-481e-81e5-752f8638ff8e

https://github.com/tf2classic/tf2classic-issue-tracker/assets/113199408/4f9de94f-d550-4c9d-86e0-819d9c39f614

**Comment by azzyr** [comment]
not a bug, this behaviour can be turned off with hud_combattext_show_when_dead 0
