### ISSUE TITLE
Messed up text and can't join servers

### ISSUE THREAD

**Issue by ValorGames** [tf2classic/tf2classic-issue-tracker#246]
I downloaded the zip file via the official website (not through github). I extracted it, and I can launch the game alright, but servers don't show up in the server browser (I can still host a server), and some of the menu text is replaced with some file name sounding text, like 'Loadout Menu' is replaced with '#Tf_Menu_Loadout'. It appears as if all the chat, class names (in loadout), weapon names, and weapon stats appear to be messed up in some way. Connecting to servers through the website doesn't appear to work either. I extracted the file using WinRAR (Not sure if this might be the cause). I have played it just fine before, but that was before I had WinRAR, I just used the built-in windows file extractor.

**Comment by Technochips** [comment]
Game is fine if you've installed it correctly. This issue was already described here: https://wiki.tf2classic.com/wiki/Troubleshooting
