### ISSUE TITLE
Missing Texture problem 

### ISSUE THREAD

**Issue by Esmusmio** [tf2classic/tf2classic-issue-tracker#25]
Hello, I installed tf2 classic and I'm having a bug with the textures, and I was wondering if anyone here can help me
![20220612170220_1](https://user-images.githubusercontent.com/54820620/173255950-51d7652a-0df9-4ed6-b999-c2b59f955060.jpg)
![20220612170243_1](https://user-images.githubusercontent.com/54820620/173255954-250caa28-9d48-45b9-bd37-c95097d92bac.jpg)
![20220612170250_1](https://user-images.githubusercontent.com/54820620/173255957-a7b113a7-1122-4fc7-a066-f7a8b9ed1317.jpg)
.

**Comment by Technochips** [comment]
This is an issue tracker, this isn't for technical support. Try the technical issues channel on the Discord.

**Comment by Esmusmio** [comment]
> This is an issue tracker, this isn't for technical support. Try the technical issues channel on the Discord.

Oh, my bad
