### ISSUE TITLE
Spy's damage resistance while cloaked only reduces damage from critical hits by 6.66%

### ISSUE THREAD

**Issue by mercurialisbetter** [tf2classic/tf2classic-issue-tracker#252]
The Rocket Launcher deals 270 critical damage. In theory, it should be reduced to 216. Instead, it is reduced to 252. This is a third of the expected damage reduction. Expected behaviour is that critical damage is reduced by 20% instead of 6.66%.

See also:
https://github.com/tf2classic/tf2classic-issue-tracker/issues/211
https://github.com/tf2classic/tf2classic-issue-tracker/issues/215

https://github.com/tf2classic/tf2classic-issue-tracker/assets/113199408/942b555d-8cc0-432f-b107-bc80e8b61895

**Comment by Torston420** [comment]
90 x 0.8 + (90 x 2) = 252, which means the critical damage bonus is not being resisted at all.
This is actually not accurate to TF2 behavior, as Gun Mettle cloak is supposed to resist critical damage as well.
![itemtest0000](https://github.com/tf2classic/tf2classic-issue-tracker/assets/30721808/228d324a-9e5e-4e54-91c9-0394c875d0af)
Live TF2 for comparison, 125 - 29 = 96 = 120 x 0.8

**Comment by Trotim** [comment]
Gun Mettle cloak resisting critical damage too seems like a Valve oversight... but alright, guess we want to be 1:1
