### ISSUE TITLE
Mod crashed

### ISSUE THREAD

**Issue by Helldtek** [tf2classic/tf2classic-issue-tracker#259]
When I starting TF2C after skip logo, modification crashed with HL2 error.
(I download from zip-archive)

**Comment by newgreenshoot** [comment]
Can you attach a screenshot of the error?

**Comment by Helldtek** [comment]
Sure, here it is.
[image: bandicam 2023-09-08 15-50-57-414.jpg]
[image: bandicam 2023-09-08 15-50-36-857.jpg]


пт, 8 вер. 2023 р. о 06:51 Chloe ***@***.***> пише:

**Comment by newgreenshoot** [comment]
These aren't attached screenshots, these are raw filenames. The issue's probably obsolete by now anyways though, closing. Feel free to reopen if you're still experiencing this.
