### ISSUE TITLE
the game crashes when trying to create/connect to a session from the main menu

### ISSUE THREAD

**Issue by SadSun32** [tf2classic/tf2classic-issue-tracker#260]
in the console, the game spams this:
"Failed to create decoder for MPE [ ui/gamestartup8.mp3]"
my specs: fedora linux 38

**Comment by newgreenshoot** [comment]
Known issue on Fedora, still looking into it. Can be mitigated by force-enabling Proton in Source SDK Base 2013 Multiplayer.

**Comment by newgreenshoot** [comment]
Closing, as this was a native Linux issue and we only support Proton now.
