### ISSUE TITLE
[TF2CDownloaderLinux] Temporary patch file never gets cleaned after update finishes

### ISSUE THREAD

**Issue by Torston420** [tf2classic/tf2classic-issue-tracker#267]
Patch files are downloaded to /var/tmp prior to extraction process, but once completed the files remain in place.
Files in /var/tmp are not automatically cleaned on reboots as the folder is intended to be persistent.
Not every distribution, install or user has supplied themselves with a way to clean this folder programmatically, ideally the installer should handle its deletion once finished as it would have lived past its usefulness in the majority of cases.

**Comment by newgreenshoot** [comment]
Wrong repo for this, there's an open issue here: https://github.com/tf2classic/TF2CDownloader/issues/40
