### ISSUE TITLE
2nd game I play and there's this error message

### ISSUE THREAD

**Issue by lemmings189** [tf2classic/tf2classic-issue-tracker#268]
**1882.269621 BlockingGetDataPointer:  Async I/O Force ambient\desert_wind_low.wav (    0.39 msec /     0.49 msec total )
**
The weapon is shaking and even disappearing for some frames, and the movments are a little buggy too.
What could be the cause of this ?
Thanks,

**Comment by newgreenshoot** [comment]
Sorry for the incredibly late response, but this is a common warning that comes from slow hard drives. It's only indicating that it took longer to load a sound from disk than it should've. This isn't a bug, you just need to defragment your drive, or upgrade to an SSD.
