### ISSUE TITLE
Rare client crash related to the Medigun on full update.

### ISSUE THREAD

**Issue by zxz41** [tf2classic/tf2classic-issue-tracker#272]
Medic's will tend to crash while healing someone after/during a full update. Happens regardless healing progression sound is enabled or disabled, and may be completely unrelated. The crash occurs in the middle of a `mult_patient_overheal_penalty` check.
It can be triggered by `record fullupdate;stop` or by `cl_fullupdate` while healing someone. It may not happen all the time.

https://github.com/tf2classic/tf2classic-issue-tracker/assets/11709919/8a3a78d2-e802-4e99-939e-19efec9f4852

**Comment by sapphonie** [comment]
Thanks! Narrowed it down to some bad logic somewhere in CTFHealSoundManager

**Comment by azzyr** [comment]
fixed for next patch, CTFPlayerShared had garbage member variables after full update. to fix i set CTFHealSoundManager::m_pPatient to NULL when a full update packet is received so HSM stops playing sounds. thanks
