### ISSUE TITLE
Chekhov's Punch consumes crits when punching (without a full crit stack)

### ISSUE THREAD

**Issue by bward2** [tf2classic/tf2classic-issue-tracker#288]
Here's how to reproduce this:

- Equip Checkhov's Punch
- Land a punch or two, storing one or two crits
- Punch the air
- A stored crit it consumed

If the player shoots their primary or secondary weapon with 1-2 crits in reserve, it makes sense that these crits are consumed. Whether the player lands their shots or miss, it makes sense that they use charges from their stored crits to fire critical shots.

When the player has their Chekhov's Punch fists active, they cannot utilize their stored crits until obtaining a full stack of three crits. If the player throws a punch which hits nothing while in possession of only 1-2 crits, a critical charge is consumed for no benefit.

This _**might**_ be intended behavior, but it feels like it may be a bug. I'll go ahead and post this here in case it's a bug.

**Comment by Trotim** [comment]
It is intended (though debated), but thanks for the report!
