### ISSUE TITLE
1000 fps issue 

### ISSUE THREAD

**Issue by eikiman** [tf2classic/tf2classic-issue-tracker#291]
https://youtu.be/4I3oDgSQNqA

https://youtu.be/OoMxTs394oM

according to shounics video tf2 gets messy with a 1000 fps on servers you created but 1000 fps is perfectly fine in valve servers however in tf2c i stutter and rubber band although with good connection and this happened on multiple servers (although the video only shows 1)

**Comment by Trotim** [comment]
I reckon that's an engine issue we can't do much about...?

**Comment by newgreenshoot** [comment]
Verified, it would require engine access, so it's outside of our scope unfortunately.
