### ISSUE TITLE
Couldn't update TF2 Classic to the newest version avaiable (2.1.3 i believe)

### ISSUE THREAD

**Issue by Shtwick** [tf2classic/tf2classic-issue-tracker#295]
As said in title, asked to do a screenshot
![image](https://github.com/tf2classic/tf2classic-issue-tracker/assets/70098892/b3338344-ac08-4d42-8550-a04d8338ca08)

**Comment by newgreenshoot** [comment]
As it reads, "there is not enough space on the disk."
