### ISSUE TITLE
ED_Alloc: no free edicts

### ISSUE THREAD

**Issue by someguylap** [tf2classic/tf2classic-issue-tracker#299]
when playing the game i go and error go kaboom the engine has politly ask us to explode we've enabled bug reporting we will take a look the error was: ED_Alloc: no free edicts i play with a huge amount of bots but in v2.1.2 it did not do the error.

**Comment by Markus-Wyand** [comment]
This happens Because of bots switching classes way too often due to "tf_bot_reevaluate_class_in_spawnroom 1"
Devs are aware of this issue.

**Comment by someguylap** [comment]
will there be a fix when 2.1.4 releases like extending the engine limits.

**Comment by newgreenshoot** [comment]
We can't safely raise the edict limit on our current engine branch, but we can fix the issue where that convar creates so many edicts in the first place.

**Comment by newgreenshoot** [comment]
The issue with tf_bot_reevaluate_class_in_spawnroom was fixed in 2.1.4.
