### ISSUE TITLE
Malicious servers can cause clients to hang on future connections

### ISSUE THREAD

**Issue by XHosi** [tf2classic/tf2classic-issue-tracker#30]
just like title said, no matter what server I try to join TF2C stops responding.

**Comment by KrzysiuLubiWode** [comment]
![Niksbigasshole — kopia](https://user-images.githubusercontent.com/107482876/173581402-54160dd2-3916-4be5-bf82-1ae400c84ff6.png)

![Niksbigasshole2](https://user-images.githubusercontent.com/107482876/173581418-7c7cc82a-5191-441c-8c6c-5d79f079644f.png)
fix i found

**Comment by chloecormier** [comment]
Common issue. We're looking into solutions. In the meantime, see: https://wiki.tf2classic.com/wiki/Troubleshooting#My_game_suddenly_freezes_or_crashes_when_joining_a_map,_when_it_didn't_before!

**Comment by TrevorRmaladesh34** [comment]
@chloecormier thats cool and all but if you don't fix it your estrogen supply will run out and you will need some rope to do a flip cause you look like a man xD
![2469250-dc8229a3387be6cd1f8603027758abf9 — kopia](https://user-images.githubusercontent.com/107484839/173588162-ccc75862-805c-4eb8-8b61-3c5851d53538.jpg)
![wasa](https://user-images.githubusercontent.com/107484839/173588181-8f2df76c-68af-4f3e-b8bd-4011a797332c.png)
