### ISSUE TITLE
[C. Captions] TF2C's Closed Captions work, but appear to be mismatched

### ISSUE THREAD

**Issue by SilentFox3** [tf2classic/tf2classic-issue-tracker#301]
To elaborate on the title; TF2C's in-game English captions appear to be directly from the [Live TF2 mod](https://gamebanana.com/mods/25151) - which still work fine in TF2C! However, it has quite a bit of bloat + captions for features not immediately supported or relevant to TF2C, like MvM or Halloween. Not a big deal, but it should be noted since TF2C really doesn't need all of them, and less is probably better for general upkeep.

Relevantly, though, there appears to be a truncated version of `closecaption_english.txt` that wasn't compiled, that appears to be somewhat cleaned up and has different text colors? I hesitate to make direct suggestions, but perhaps it would be wise to compile and use it as a base rather than the mod version, if for no other reason than to cut out unused lines and make future localization easier...?

![](https://i.imgur.com/LlEUvqx.png)
_(`closecaption_english_tf2c.dat` is a compiled and renamed version of `closecaption_english.txt`, and it's noticably smaller!)_

All said, the mod version DOES work fine, so this is a very minor nitpick. Apologies!

**Comment by newgreenshoot** [comment]
My fault, we accidentally shipped the captions we built from the mod release whenever we were testing it rather than the modified version we were later sent. We'll get it fixed in the next patch, thanks.

**Comment by SilentFox3** [comment]
This appears to finally be fixed with TF2C v2.1.5 - marking as closed. Thank you!
