### ISSUE TITLE
This application must be placed in the root direction of the mod in order to fuction correctly!

### ISSUE THREAD

**Issue by Tartimus** [tf2classic/tf2classic-issue-tracker#306]
![error](https://github.com/tf2classic/tf2classic-issue-tracker/assets/159479170/90d84f9a-3840-421b-846c-3559f1c6a599)
how do i fix this?

**Comment by Technochips** [comment]
See this: https://github.com/tf2classic/tf2classic-issue-tracker/blob/main/README.md
