### ISSUE TITLE
Archive version of tf2classic does not include scripts folder.

### ISSUE THREAD

**Issue by TOAGAME** [tf2classic/tf2classic-issue-tracker#307]
The archive version of tf2 classic has no scripts folder which is required to launch the game, otherwise the game crashes after the intro movie.

Whenever I try to open up tf2 classic with the archive version installed, it crashes with the error that it can't find objects.txt which is in the scripts folder.

**Comment by azzyr** [comment]
LZMA archives have issues with Windows' unzip tool. Next patch will use Deflate instead, which should be compatible with everything.

**Comment by TOAGAME** [comment]
alright, but please do double check that the scripts folder is there because I use a program called breezip for extracting zips and rars

**Comment by TOAGAME** [comment]
yeah so apparently I had actually extracted the zip wrong multiple times, either that or the zip was downloaded wrong, because there were actually a few VPK files missing from the old version I had
