### ISSUE TITLE
Game closes as soon as i open it

### ISSUE THREAD

**Issue by PeurPioche7830** [tf2classic/tf2classic-issue-tracker#310]
Game closes as soon as i open it
i tried repairing using the installer, deleting the installer and re-download a fresh one but nothing works
(btw, there is no error mess&age, it goes trough the intro fine but then it loads and closes, just like that

**Comment by newgreenshoot** [comment]
Too vague for this issue tracker, you'd have to seek support in the Discord, sorry.
