### ISSUE TITLE
I give up

### ISSUE THREAD

**Issue by nieumiemwymyslicnazwy** [tf2classic/tf2classic-issue-tracker#317]
To be honest, I don't care that this isn't a bug raport. I just wanted to say that i give up playing this game.
Thay say tf2 is fun, but for me it isn't. I have but aim. When i play more and more i don't see any progress in aiming hitscan or projectile.
This game makes me feel like a loser. So I quit, but thath doesn't mean that the concept of this game suck. I like the concept. I just suck at playing and i don't think i'll have fun playing it ever.

**Comment by MOPSSLIDANA** [comment]
sad
