### ISSUE TITLE
corrupted hud files

### ISSUE THREAD

**Issue by mkwiifunny** [tf2classic/tf2classic-issue-tracker#319]
it doesnt matter what i do or how many times i reinstall, there are a combination of custom hud assets stuck in my game that i cannot remove by any means, any time i try to use a custom hud through the custom folder it conflicts and causes issues,such as not being to change weapons in grid mode, buttons lose visibility, meters are incorrectly placed, and the timers are missing texture checkboards
![Half-Life 2 DM-04-06-2024 0-01-06-611](https://github.com/tf2classic/tf2classic-issue-tracker/assets/166181788/fbe76839-ef0b-4b03-a243-22acc7691b96)
![Half-Life 2 DM-04-06-2024 0-00-07-360](https://github.com/tf2classic/tf2classic-issue-tracker/assets/166181788/4d83abf6-9d5f-4b3a-bda6-b6fb6b0f0464)
proof of corruption

**Comment by bobatealee** [comment]
this is a problem with the hud, not the game
