### ISSUE TITLE
[Material] Engineer's left hand on Viewmodels doesn't have a lightwarp at all

### ISSUE THREAD

**Issue by SilentFox3** [tf2classic/tf2classic-issue-tracker#321]
Hey! This has been annoying me for years, but I sorta just expected it to be fixed eventually. Nevertheless, I'll mention it again -

`engineer_handl.vmt` controls the visual properties of Engineer's left hand (and right arm's forearm skin), and is very similar to `engineer_handr_red.vmt`, but with one big difference - the lightwarp is commented out and has no replacement. Since it didn't have a replacement, it just uses the default HL2 soft lighting, which looks... not, very good, in TF2C.

![](https://i.imgur.com/3fzTbg8.png)
![](https://i.imgur.com/n4lN0vv.png)

This is an easy fix! Most classes use `pyro_lightwarp.vtf` for generic TF2 lighting (or `lambert_lighting.vtf` for post TF2C v2.1.2), so just provide that as a lightwarp and it works perfectly, like so;
```	"$lightwarptexture" "models/player/pyro/pyro_lightwarp"```
```	"$lightwarptexture" "models/player/pyro/Lambert_lightwarp"```

![](https://i.imgur.com/woZsu8H.png)

**Comment by newgreenshoot** [comment]
Our initial assumption was that it'd been like this for years, but it seems like this was changed by accident(?) in a relatively recent development cycle. It's been reverted and should have the lightwarp restored in 2.2.

**Comment by SilentFox3** [comment]
As of TF2C v2.2.0, this issue seemingly still isn't fixed. Engineer's left hand in viewmodels still has the default HL2 lighting instead of using a player lightwarp. I'd provide a picture, but it looks completely identical to how it did in my examples from above taken in TF2C v2.1.5.

If there was a fix committed, it doesn't appear to have made it to release - was it reverted? Anyway, request to reopen this issue if possible, since I'm not able to reopen closed issues, myself. Apologies.

**Comment by newgreenshoot** [comment]
Seems like this was fixed in beta *after* we had branched it off into a separate repo for 2.2, and we never cherrypicked it. Clerical error on our part, it'll be in the next hotfix though so I'll leave this closed.
