### ISSUE TITLE
Game force closing issue

### ISSUE THREAD

**Issue by Tails-X-Fries** [tf2classic/tf2classic-issue-tracker#324]
Whenever I launch TF2Classic, it opens just fine, but then after about 3 to 5 seconds, it force closes itself. When I tried to look at the downloaded command console to get the game, it says everything is fine, from everything updated to having no corrupt code, and yet every launch I do, the game force closes itself

**Comment by newgreenshoot** [comment]
Too vague for this issue tracker, you'd have to seek support in the Discord, sorry.
