### ISSUE TITLE
Weird color filters in random spots on 2fort

### ISSUE THREAD

**Issue by MisterzPvP** [tf2classic/tf2classic-issue-tracker#327]
The new update to 2fort for some reason added weird random spots in the intel rooms which apply a heavy color filter to your view. I would assume these aren't intentional.

In the blu intel room, standing in this corner here applies a color filter:
![image](https://github.com/tf2classic/tf2classic-issue-tracker/assets/109600732/13167a6d-3387-4763-8bcc-6c4d9016cf94)

In the red intel room, standing here applies a color filter:
![image](https://github.com/tf2classic/tf2classic-issue-tracker/assets/109600732/7133d0e1-6cba-4bec-bfd2-f0260cbb2e48)

**Comment by newgreenshoot** [comment]
Known issue, this is worked around on VaultF4 but it still affects third-party servers, we'll have it fixed in the next patch.
