### ISSUE TITLE
[TF2C] Heavy has infinite Sandviches (replicatable)

### ISSUE THREAD

**Issue by GodotUK** [tf2classic/tf2classic-issue-tracker#337]
Latest version as of time of posting. 

**1. Start eating your sandwich.
2.  As soon as you are taunting spam right click (Or your sandvich drop key).**

If you attempt to drop the sandvich as soon as your taunt is ending you will spawn an extra sandvich, negating cooldown. 

Hopefully it is an easy fix. 

Thanks,
- From https://steamcommunity.com/id/Letswaitforhimoka/
Q. If this gets fixed do i get one of those super cool badges in game!?

**Comment by Technochips** [comment]
To be very clear, the Sandvich is meant to have:
* no cooldown when eating it (can eat as many times in a row)
* a cooldown when throwing the sandvich (causes the sandvich to be unusable for it to recharge)

Does this bypass the throw cooldown?

**Comment by GodotUK** [comment]
Hi Techno, if the sandvich is intended to be infinite then that's fine and there is no bug to report. I was in a game where people on VC were losing their minds over it so I figured I would make a report just in case, seems like its an intended mechanic then.

Thanks!

**Comment by Technochips** [comment]
Well, good to know.
