### ISSUE TITLE
Using weapon attribute "add_onhit_ubercharge" with negative value will decrease ubercharge percentage past 0%

### ISSUE THREAD

**Issue by MasonatorRoblox** [tf2classic/tf2classic-issue-tracker#34]
As the title says. 
I was using it to make a Medic weapon which sacrifices uber for extra damage, and I found that hitting enemies at low/no uber would drop the ubercharge percentage below zero.
Image of weapon stat:
![image](https://user-images.githubusercontent.com/42453670/174564420-cfb2cfaf-69ca-43ac-a80c-8703e43ab8a9.png)
Negative uber:
![image](https://user-images.githubusercontent.com/42453670/174565071-d2e15d33-f912-4a4b-a803-e1443a5386f3.png)
You guys may have already fixed this one, but thought I may as well post it, since ubercharge cost on hit is a concept that custom weapon creators might want to use.

**Comment by Trotim** [comment]
Just fixed this and clamped uber from this function to min 0%
While I was at it, I also limited add_cloak_on_hit to not go below 0% cloak
Thanks~

**Comment by bobatealee** [comment]
fixed
