### ISSUE TITLE
How to install TF2C on Linux now that the native client support is gone?

### ISSUE THREAD

**Issue by presario42** [tf2classic/tf2classic-issue-tracker#344]
I want to know how do i do it, i am a bit puzzled with the instructions provided with the website as they're a bit empty.

**Comment by newgreenshoot** [comment]
You have to force Proton as the compatibility tool for Source SDK Base 2013 Multiplayer. At that point, Team Fortress 2 Classic should launch fine, provided that it's installed correctly into your sourcemods folder.
