### ISSUE TITLE
Explosions from tf_point_weapon_mimic ignore set splash radius.

### ISSUE THREAD

**Issue by 111112oo** [tf2classic/tf2classic-issue-tracker#349]
tf_point_weapon_mimic has an option to set the explosion radius but it does not work. Regardless of what it is set to, the explosion will always reach about 144 units from the centre. I have only tested this with rockets currently. This bug DOES exist in live TF2.

In the below test map on the right side (ignore the left side, for another bug report) is a bunch of tf_point_weapon_mimics with various settings, but they all seem to explode the same radius.
[test_tf2cexplosionradius.txt](https://github.com/tf2classic/tf2classic-issue-tracker/files/15183784/test_tf2cexplosionradius.txt)
(Rename to .vmf plaintext yada yada)

**Comment by azzyr** [comment]
was broken for rockets only. fixed in 2.1.5, thx

**Comment by 111112oo** [comment]
Can confirm fixed in 2.1.5!
