### ISSUE TITLE
found a missing texture in vip_badwater

### ISSUE THREAD

**Issue by SomethingDeveloper** [tf2classic/tf2classic-issue-tracker#375]
there's a missing texture on the new shortcut.
![2024-06-10](https://github.com/tf2classic/tf2classic-issue-tracker/assets/68327627/1f6469d4-bfd8-4e30-8dad-d8e9e4d0877d)

**Comment by newgreenshoot** [comment]
We forgot to pack this. It's hotfixed on VaultF4 using download lists but should be included properly in the next update, thanks.
