### ISSUE TITLE
[bug] odd reflections in REDs intelligence room on 2Fort

### ISSUE THREAD

**Issue by 1resubuhtig** [tf2classic/tf2classic-issue-tracker#384]
![Odd reflections in REDs intelligence room on 2Fort](https://github.com/tf2classic/tf2classic-issue-tracker/assets/151361703/dbc8022e-3cb1-42bd-a4a1-45fc0d2b60f3)

**Comment by 1resubuhtig** [comment]
the whole RED logo is reflected on the glass doors even though the glass shouldn't reflect it fully

**Comment by 111112oo** [comment]
Here the RED logo is to the right of the glass, thus it is being reflected. Not a bug.

**Comment by 1resubuhtig** [comment]
it is reflected, but if you move to the side, you can see reflections that shouldn't be there. like, the entire logo on the floor doesn’t face the reflective glass the way the reflections appear. i took a screenshot to demonstrate the incorrect reflection of the logo, welp, maybe it’s not very noticeable, sorry about that. it’s just a minor detail, but in reality, reflections don’t behave that way.

from A in RELIABLE to end of the floor logo there shouldn't be reflections on the glass. but its true that source is really old game engine, so yeah, its maybe not a bug, idk tbh
