### ISSUE TITLE
Map .cfg files for long map names are getting cutoff and thus not read on map load.

### ISSUE THREAD

**Issue by 111112oo** [tf2classic/tf2classic-issue-tracker#430]
I run a map I worked on on my server named dr_champions_destiny_v2b. I also have a cfg file for this map to set important cvars when this map gets loaded. However, the console prints an error of `Error, bad server command exec dr_champions_destiny_v2b.c` whenever the map is loaded, showing the .cfg suffix being cut off, resulting in my cvars not being set. I can however load this manually with `/sm_rcon exec dr_champions_destiny_v2b.cfg` ... I have .cfg files for a few other maps that all apply fine, it's just this map which it fails on. My assumption is there being a name limit in place here that's smaller than the actual name limit for maps.
Here is the .cfg in question: 
[dr_champions_destiny_v2b.txt](https://github.com/user-attachments/files/16957674/dr_champions_destiny_v2b.txt)

**Comment by azzyr** [comment]
Fixed in 2.2
