### ISSUE TITLE
Flamethrower alt-fire spawns harmless fire particles when airblast is disabled

### ISSUE THREAD

**Issue by azzyr** [tf2classic/tf2classic-issue-tracker#49]
How to replicate:
- Disable airblast, either via `tf2c_airblast` cvar or with `airblast_disabled` attribute
- Hold primary fire, Hold secondary fire at the same time, then let go of primary fire

The fire particle will still appear for as long as you hold secondary fire.
It's important to note that the particle does **ZERO damage, as the hitboxes do not spawn.**

**Comment by bobatealee** [comment]
fixed
