### ISSUE TITLE
Spy class UI doesn't update after being killed with Dead Ringer

### ISSUE THREAD

**Issue by ImInLoveWithProgramming** [tf2classic/tf2classic-issue-tracker#5]
When you get killed it should be updated to the spy UI, for some reason tho, if i we're to take the Scout for example, and get "fake" killed with the Dead Ringer, the UI will remains as Scout, while in fact I'm not and this is very confusing.

Have a nice day.

**Comment by chloecormier** [comment]
The Dead Ringer isn't an item in TF2 Classic. You should report this to the custom weapons server you're playing on.

**Comment by ImInLoveWithProgramming** [comment]
Hello, I'm sincerely sorry! I thought you're the ones working on theses.
