### ISSUE TITLE
Demo man grenades not hitting.

### ISSUE THREAD

**Issue by AlternateLands** [tf2classic/tf2classic-issue-tracker#52]
While playing demo man I have encountered a weird thing with the grenade launcher. 

While shooting a sentry some grenades hit the sentry and detonate, while a select few grenades hit the sentry and bounce onto the floor.
All these shots are direct hits on the sentry but a number of them somehow count as having hit an obstacle of some sort.

Either the grenade launcher is having issues or something on the sentry is counted as an obstacle such as a wall, causing them to bounce off instead of doing their usual 100 damage.

I hope this issue can be further explained to me or fixed as of why this is happening. Because I don't remember sentries counting as something that grenades bounce off of.

**Comment by Trotim** [comment]
Fixed next version (as far as I can tell). There was one case where grenades could find themselves inside an object and un-stuck themselves in VPhysicsUpdate before VPhysicsCollision could do its thing, so the grenade's Touch function never happened

**Comment by sapphonie** [comment]
This might *also* be an issue with not calling UTIL_SetSize after setting custom projectile models? Maybe?

**Comment by bobatealee** [comment]
Fixed as of 2.0.4: https://tf2classic.com/?id=5610
