### ISSUE TITLE
Uber Charge delay/not working as intended.

### ISSUE THREAD

**Issue by AlternateLands** [tf2classic/tf2classic-issue-tracker#53]
I have seen this bug happen two times using both mediguns. 

Pressing m2 when an uber is ready, does not activate the uber at all. The uber can only be activated by weapon swapping to another weapon and back to the medigun, causing it to uber instantly.

This bug causes the uber to be delayed and fixed by weapon swapping, causing many issues in gameplay with medic.

I have not seen any factors that can cause this bug, other than random chance as both times this bug happened I was using different mediguns and melee.

**Comment by Trotim** [comment]
Fixed in 2.1

**Comment by bobatealee** [comment]
fixed
