### ISSUE TITLE
"Silence the audio while the game window is in the background." Not working trough interactive menu.

### ISSUE THREAD

**Issue by LifeDreamer24** [tf2classic/tf2classic-issue-tracker#54]
Simply not working on my end. Should toggle `snd_mute_losefocus` between `1` and `0` but does not change upon applying changes neither clicking on `OK`.

Have a wonderful day from Canada and keep up the amazing development of this game 👍
/Simon

**Comment by chloecormier** [comment]
Dupe of #3 (which is already fixed)
