### ISSUE TITLE
Using raw mouse input on Linux makes classes in loadout menu spin too fast

### ISSUE THREAD

**Issue by Alex-1000** [tf2classic/tf2classic-issue-tracker#57]
Old bug from live TF2 (but exists in TF2C too), character preview at inventory makes, _well_, character, spin at extremely high speed.
To recreate bug, you just need to enable raw mouse input and try to spin character in inventory menu (and have Linux, I guess).

**Comment by azzyr** [comment]
not really our bug. this is a bug with the SDL version packed with SDK2013, to fix you will have to remove that binary so it uses your system's
