### ISSUE TITLE
Clipless Coilgun messes up ammo on Overcharge Explosion

### ISSUE THREAD

**Issue by azzyr** [tf2classic/tf2classic-issue-tracker#59]
On any weapon using the `tf_weapon_coilgun` item_class, setting the attribute `mod max primary clip override` to the value `-1` will result in the following bug when Overcharging: 

- The overcharged shot does not consume any ammo
- Ammo is set to 254 permanently

The actual remaining clip seems to be unaffected and is consumed normally when firing

Clip is set back to normal when touching a resupply cabinet or respawning

Demonstration video
https://cdn.discordapp.com/attachments/971405552028631130/1001292144063021128/coilgun.mp4

**Comment by Trotim** [comment]
Fixed next version. While I was at it, I also gave `tf_weapon_coilgun` `mod_charge_time` support, and fixed `mult_dmg` being limited by a hardcoded charged damage cap of 75
