### ISSUE TITLE
A virus in game? - Ransom your personal files are encrypted

### ISSUE THREAD

**Issue by rover414si** [tf2classic/tf2classic-issue-tracker#62]
I jsut got into game today and as soon as i get in to a offical US randomizer server my weapon slot backgrounds has an disturbing image of an mans butt being open, it has a text saying your personal files are encrypted. Please help me im afraid if this a virus. I never had this in TF2. My discord is Rover#8970 i deleted the game entirely.

**Comment by Trotim** [comment]
Not a virus. The images are picked for shock value. Simply deleting the `downloads` folder inside the `tf2classic` folder would have sufficed, but I don't blame your reaction.

We have a PSA posted on Discord:

> A few servers has appeared which floods your downloads with unwanted files when you join them, to both brick your game and/or scam you. They may download or show shock pictures (gore...), and tell you that your computer has been infected by a ransomware. However, these servers physically cannot do anything to your computer, other than download said files, brick or alter your current TF2C install through the weapon list.
> 
> If you accidentally joined one of these servers, the files will permanently stay on your computer, and the server's effects will stay until you manually delete them. To fix all of this, simply delete the "download" folder from your tf2classic folder, usually located in: C:\Program Files (x86)\Steam\steamapps\sourcemods\tf2classic
> 
> These servers hides in plain sight as regular servers (e.g. Knockout, VaultF4) with a positive player count. To see if they're fake, simply right click the server, click properties and see if the player list seems legit or not (is it not responding? do all the players have the same identical amount of time?)
> 
> In the mean time, please exclusively use either the official server list in the main menu, or this verified server list: https://wiki.tf2classic.com/serverlist/
> 
> If you want to block the fake servers permanently, either block their IPs at port :0, or import the blacklist that's listed at the bottom of the page in the link above to block all currently known fake servers.

**Comment by sapphonie** [comment]
Fixed in next update
