### ISSUE TITLE
Airblasting players as pyro does not fire network event

### ISSUE THREAD

**Issue by Crysoskis** [tf2classic/tf2classic-issue-tracker#63]
When airblasting a player or object as Pyro, the event object_deflected does not fire when it should.

Steps to reproduce:
1. Start game with a bot player
2. Turn on sv_cheats
3. Set net_showevents to 2
4. Harm or otherwise interact with bot, see if gameplay event info (such as player_hurt) is shown in console
5. Airblast player, object_deflected event does not fire.
Note: Same applies to airblasted rockets and other projectiles.

**Comment by Trotim** [comment]
Yep TF2C simply didn't send the event (because we didn't use it). Next version will force the event to send regardless so server plugins can use it
