### ISSUE TITLE
servers, and bots

### ISSUE THREAD

**Issue by tf2fan2231** [tf2classic/tf2classic-issue-tracker#72]
i can;t create a server with bots or play on public servers

**Comment by sapphonie** [comment]
> Issues should be easily reproducible, and clearly the fault of the game. If you're having personal issues regarding the game, check the [Troubleshooting page](https://wiki.tf2classic.com/wiki/Troubleshooting) and/or ask in the #technical-issues channel of our [Discord](https://discord.gg/3zMk4vn).

If you have a way to consistently reproduce this with detailed instructions, please reopen this issue.
