### ISSUE TITLE
Headshot not registering issue

### ISSUE THREAD

**Issue by blockedsheep** [tf2classic/tf2classic-issue-tracker#8]
When headshotting an opponent, most of the time it doesn't register therefore it does not deal any damage & leaves a blood stain on their head

**Comment by bobatealee** [comment]
This sounds like a network issue. Are you sure it's not due to lag on your or the server's side?

**Comment by blockedsheep** [comment]
Not at all, server's seem to be fine & same goes for ping (50 ping). I've encounted other people having the same issue

**Comment by blockedsheep** [comment]
Right, but it happens much less in live TF2. It does that alot more in TF2Classic

**Comment by Trotim** [comment]
Next version does change headshot behavior to no longer play a crit sound clientside, instead always waiting for the server to agree that it was one first. Should lower the chance of this occurring.
