### ISSUE TITLE
game randomly lowers fps for a few seconds

### ISSUE THREAD

**Issue by sava2808** [tf2classic/tf2classic-issue-tracker#81]
sometimes when im playing, the game just randomly goes to very low frame rates, like 20 fps, with no noticeable thing that causes it. after a few seconds though it comes back to the regular 60 fps. very annoying

**Comment by chloecormier** [comment]
Possibly related to tf2c_muzzlelight if you have it enabled? It can cause abrupt severe performance drops the way you're describing.
