### ISSUE TITLE
in some places emo textures

### ISSUE THREAD

**Issue by Netis01** [tf2classic/tf2classic-issue-tracker#84]
![image](https://user-images.githubusercontent.com/113846045/190913940-252de871-de47-4609-9e12-7a4effbca357.png)
![image](https://user-images.githubusercontent.com/113846045/190914145-086648ca-0fef-4381-9f41-fe9f8de3b06a.png)
![image](https://user-images.githubusercontent.com/113846045/190914190-c72d9687-6acd-49bd-9acf-8e8be44d8979.png)
![image](https://user-images.githubusercontent.com/113846045/190914242-bf5fb400-e2ee-4082-9509-05b222f7af53.png)

**Comment by chloecormier** [comment]
You likely did not let the game finish extracting. Re-run TF2CDownloader and allow it to run until it announces that it's finished. Seek further help in the #technical-issues channel on the Discord rather than the issue tracker.
